# Generated by Django 4.2 on 2025-05-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('available_tickets', models.PositiveIntegerField(default=100, verbose_name='Доступно билетов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Правила посещения')),
                ('event_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу мероприятия')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя посетителя')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram (username)')),
                ('booking_date', models.DateField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date'],
            },
        ),
    ]
