# Generated by Django 5.2.1 on 2025-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
