# Generated by Django 5.2.1 on 2025-05-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_favoriteevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteevent',
            options={'ordering': ['-created_at']},
        ),
    ]
