# Generated by Django 5.2.1 on 2025-05-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя посетителя')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('user_telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram (username)')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('status', models.CharField(choices=[('BOOKED', 'Забронировано'), ('CANCELLED', 'Отменено'), ('CONFIRMED', 'Подтверждено')], default='BOOKED', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('user_email', 'event')},
            },
        ),
    ]
